### ISSUE TITLE
Is the AggregateAnalzyer thread safe? 

### ISSUE THREAD

**Issue by pburrows** [knuppe/SharpNL#13]
Can the same instance of the AggregateAnalzyer be used on different threads? Is this recommended? Or should each thread create its own instance of the AggregateAnalzyer?

**Comment by knuppe** [comment]
The opennlp itself is not designed to share the same tool between multiple threads.

Unfortunately I have to talk in theory, because never tested on more than one thread. From what I know of the code, the model can be shared in multiple threads, and theoretically, you can use a "trick".

So you create one analyzer per thread, but all instances share the same model instance.
eg:

```csharp
var sentModel = new SentenceDetector.SentenceModel(@"c:\...\en-sent.bin");

var aggThread1 = new AggregateAnalyzer {
    new SentenceDetector.SentenceDetectorAnalyzer(new SentenceDetectorME(sentModel))
};

var aggThread2 = new AggregateAnalyzer {
    new SentenceDetector.SentenceDetectorAnalyzer(new SentenceDetectorME(sentModel))
};
```

but remember, it's good to test because I never tested it :stuck_out_tongue:

**Comment by pburrows** [comment]
Thanks, Knuppe. I will experiment and see what happens. 
Sharing the model might be ideal, because the expensive part is actually loading the model.

**Comment by Sicos1977** [comment]
What you can do when loading is expensive is to make a wcf windows service that hosts the analyzer and expose it through soap. This way you just make a connection with the service and let it return what you need. I do this in a project because of the same issue.

But I don't know what kind of program you are making so I don't know if this is an option for you

**Comment by knuppe** [comment]
@pburrows, did you managed to evolve with the tests? I would like to know! :grimacing:

**Comment by pburrows** [comment]
Hey @knuppe , sorry I never saw your question. I tried creating it on demand, and it is fast and is not running into any threading issues. I am loading en-sent, en-token, and en-pos-maxent and not running into any issues.
