### ISSUE TITLE
Trying to build Portable (pcl) assembly?

### ISSUE THREAD

**Issue by dgerding** [knuppe/SharpNL#36]
Hi,
I thought I had done this in the past.  And I see the sln referencing Mono - but when I try and target PCL I'm getting errors.  Just wondering if I'm right that a PCL compatible build is possible?

Thanks,
Dave G

**Comment by knuppe** [comment]
Hi Dave, sorry for the late reply. 

I was trying to port the library to [.net standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) some time ago, but the standard was very new, there was a lot of bugs and shenanigans, so I quit for a while. 

The PCL and .net core are deprecated these days, so I'll try to implement the library in the .net standard again. I have abandoned the Windows ecosystem, so I need to configure my development environment in linux, also there is a lot of code to change so that the library is compatible with the current version of opennlp, but it should definitely be done in .net standard.

**Comment by TechnikEmpire** [comment]
@knuppe I've just managed to move the core library over to .NET standard and all tests are passing. I can do a PR if you'd like.

**Comment by dgerding** [comment]
@TechnikEmpire I'll happily jump over to your .NET Standard build... and thanks!  Is it the latest SharpNL in your repos? (And thanks again for making my holidays a little brighter :) )

**Comment by TechnikEmpire** [comment]
@dgerding yep it's the latest version. I created an unofficial nuget package you should find if you search sharpnl.

**Comment by knuppe** [comment]
@TechnikEmpire wonderful! I will check your pull request as soon as possible.

**Comment by TechnikEmpire** [comment]
If/when @knuppe pulls those changes I'll hide my nuget repo. I don't want to create fragmentation, I just wanted to make something available for other packages of mine in the meantime.

**Comment by TechnikEmpire** [comment]
@knuppe I closed it because I had started making other small changes and because I blew away the mono solution so appveyor fails now. So, I'd have to create a different branch, restart PR and then we'd have to figure out how to change up appveyor. In order to get proper tooling support, the main solution and project had to be upgraded to VS 2017 so there's quite a few things left to consider.

**Comment by knuppe** [comment]
@TechnikEmpire don't worry, I'm reviewing manually your pull request, so var everything is working!

Were you able to make the unit tests work on VS2017? It seems to me, that NUnit3 simply does not work with VS2017 when using .net standard 2.0 or .net core :disappointed:

**Comment by TechnikEmpire** [comment]
@knuppe I upgraded to latest nunit and then pulled down the nunit tools package and manually ran unit tests on the command line. I'm ashamed to say so given my extensive work in .net but I've never used nunit lol so I'm not sure if it's supposed to have an integrated build target that executes it automatically or not.

**Comment by TechnikEmpire** [comment]
That's what the latest docs told me to do anyway. Tells you to install the package that bundles the executable and then run it on the command line manually. So I dunno you'd have to tell me what it used to do/should do.

**Comment by knuppe** [comment]
Yesterday I released the new version to NuGet! Have fun :ok_hand:

**Comment by dgerding** [comment]
:).  Thanks!
________________________________

**Comment by dgerding** [comment]
Hi All,
I’m sorry to report I can reproduce a case where simply adding the published Nuget to a new XamForms templated project breaks the Android app.  Solution compiles, and runs on iOS and UWP but crashes on Android on startup.

(Log from Android device attached.)

I’m running into the same problem on my real work project and wanted to make sure it wasn’t something in my code so I made this clean test solution (attached).  I included the git where I stepped through adding SharpNL to reproduce.

The only link I could find that seemed related was:
https://developercommunity.visualstudio.com/content/problem/152947/xamarin-android-run-error-could-not-load-assembly.html

Following the “fix” in the link didn’t work.

I also tried pulling a copy of SharpNL and updating the System.Security.Permissions by a single dot release to latest and then using that new SharpNL dll instead of the nuget release – but still crashes.

Xamarin Android seems to be having the hardest time moving to .net standard.   I’m working with some of the Xamarin/MS devs on a (maybe) related issue trying to get Azure Mobile client to work. If I find anything there I will let you know.

If I can help somehow please let me know.

Do you want me to post this as an issue or wait?

Thanks,
Dave Gerding
