### ISSUE TITLE
Referenced assembly 'SharpNL' does not have a strong name

### ISSUE THREAD

**Issue by Sicos1977** [knuppe/SharpNL#5]
Hi,

Can you compile and sign the SharpNL assembly that is on nuget? I use strong names in my project and otherwise it is impossible to use the SharpNL assembly.

Also another question... is there a .NET 4.0 version available?

Greetings,
Kees van Spelde

**Comment by knuppe** [comment]
Hello Kees,

Thank you for reporting the problem, the initial release was more for testing purposes. Right now I have little time to work in the library, but I'll try.

The Parser must be fixed fist, because the version that I have on my dev machine contains some changes and new features and I would not like to use an old version to correct this issue.

To downgrade to .NET 4.0 version we would need to change some things... I think the most changes are the read-only collections. It’s possible, but I can't promise to do this right now.

**Comment by knuppe** [comment]
Well, the Parser has been fixed. 
:grin:

**Comment by Sicos1977** [comment]
Never mind about the .NET 4.0 version. I just upgraded my project to .NET 4.5 and that fixed my 4.0 problem :-) , And at the moment I just signed the assembly myself. I got your latest version from Github and compiled it.
